---
- hosts: all
  remote_user: root
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx
    - name: Installs mysql server
      apt: pkg=mysql-server state=installed update_cache=true
      notify:
        - start mysql
  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: start mysql server
      service: name=mysql state=started
