---
- hosts: all
  remote_user: root
  vars:
    username: www-data
  tasks:
    - name: Installs git
      apt: pkg=git state=installed update_cache=true

    - name: Installs python pip
      apt: pkg=python-pip state=installed update_cache=true

    - name: Installs python development headers and libraries 
      apt: pkg=libpython-dev state=installed update_cache=true

    - name: Installs required mysql libraries for python 
      apt: pkg=libmysqlclient-dev state=installed update_cache=true

    - name: Install the Python MySQLB module
      pip: name=mysql-python

    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: Installs mysql server
      apt: pkg=mysql-server state=installed update_cache=true
      notify:
        - start mysql

    - mysql_db: name=wordpress state=present

    - name: Installs Wordpress
      apt: pkg=wordpress state=installed update_cache=true
      notify:
        - restarted nginx

    - name: Check Nginx configs exist
      stat: path=/etc/nginx/.git
      register: git_exists

    - name: Remove default Nginx configs
      file:
       path: /etc/nginx
       state: absent
      when: not git_exists.stat.exists

    - name: Clone Nginx configs
      git:
       repo: https://github.com/archbungle/nginx.git
       dest: /etc/nginx
       version: master
       force: yes
      when: not git_exists.stat.exists

    - mysql_user: name=wordpress password=pressword priv=*.*:ALL state=present

    - name: Symlink default site
      file: 
       src: /etc/nginx/sites-available/mysite
       dest: /etc/nginx/sites-enabled/default
       state: link
      notify:
        - restarted nginx 

  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: start mysql server
      service: name=mysql state=started
